using System.Text.Json;
using UnifiedToolkit.Conversion.FirstEdition;
using UnifiedToolkit.Conversion.FirstEdition.Pilots;
using UnifiedToolkit.KnowledgeBase;

namespace UnifiedToolkit.Runtime;

public static class FirstEditionShipPackagePlanner
{
    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };
    private static readonly HashSet<string> ValidBaseSizes = new(StringComparer.OrdinalIgnoreCase) { "small", "large", "epic" };

    public static FirstEditionShipPackagePlanDocument Build(
        string repositoryRoot,
        FirstEditionRepository repository,
        string mappingVersion,
        UnifiedKnowledgeBase knowledgeBase)
    {
        repositoryRoot = Path.GetFullPath(repositoryRoot);
        var shipLinks = LoadLinks<ShipLinkDocument>(Path.Combine(repositoryRoot, "ukb", "ship-links.json"));
        var pilotLinks = LoadLinks<PilotLinkDocument>(Path.Combine(repositoryRoot, "ukb", "pilot-links.json"));
        var assetsById = knowledgeBase.Domains.Assets
            .GroupBy(x => x.AssetId, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(x => x.Key, x => x.First(), StringComparer.OrdinalIgnoreCase);

        var document = new FirstEditionShipPackagePlanDocument
        {
            RepositoryRoot = repositoryRoot,
            MappingVersion = mappingVersion,
            KnowledgeBasePath = Path.Combine(repositoryRoot, "ukb", "knowledge-base.json")
        };

        foreach (var pilot in repository.Pilots
                     .OrderBy(x => x.Faction, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(x => x.ShipId, StringComparer.OrdinalIgnoreCase)
                     .ThenBy(x => x.Name, StringComparer.OrdinalIgnoreCase))
        {
            var ship = repository.FindShip(pilot.ShipId);
            document.Packages.Add(BuildPackage(pilot, ship, shipLinks, pilotLinks, knowledgeBase, assetsById));
        }

        PopulateSummary(document, repository);
        return document;
    }

    private static FirstEditionShipPackagePlan BuildPackage(
        FirstEditionPilot pilot,
        FirstEditionShip? ship,
        ShipLinkDocument shipLinks,
        PilotLinkDocument pilotLinks,
        UnifiedKnowledgeBase knowledgeBase,
        IReadOnlyDictionary<string, KnowledgeBaseAsset> assetsById)
    {
        var plan = new FirstEditionShipPackagePlan
        {
            PackageId = $"{Normalize(pilot.Faction)}/{Normalize(pilot.ShipId)}/{Normalize(pilot.Id)}",
            ShipId = pilot.ShipId,
            ShipName = ship?.Name ?? "",
            PilotId = pilot.Id,
            PilotName = pilot.Name,
            Faction = pilot.Faction,
            BaseSize = ship?.Size ?? "",
            PilotSkill = pilot.PilotSkill,
            SquadPointCost = pilot.SquadPointCost,
            Unique = pilot.Unique,
            UpgradeSlots = pilot.UpgradeSlots.ToList()
        };

        if (ship is null)
            plan.ValidationErrors.Add($"Pilot references unknown ship '{pilot.ShipId}'.");
        else if (!ValidBaseSizes.Contains(ship.Size))
            plan.ValidationErrors.Add($"Invalid First Edition base size '{ship.Size}'. Only Small, Large and Epic are allowed.");

        var shipLink = FindShipLink(shipLinks, pilot.ShipId);
        var pilotLink = FindPilotLink(pilotLinks, pilot);

        plan.Requirements.Add(ResolveLinkedRole(ShipPackageRoles.ShipModel, true, shipLink?.AssetRoles, assetsById, pilot, ship));
        plan.Requirements.Add(ResolveLinkedRole(ShipPackageRoles.ShipTexture, true, shipLink?.AssetRoles, assetsById, pilot, ship));
        plan.Requirements.Add(ResolveLinkedRole(ShipPackageRoles.DialTexture, true, shipLink?.AssetRoles, assetsById, pilot, ship));
        plan.Requirements.Add(ResolveLinkedRole(ShipPackageRoles.PilotCard, true, pilotLink?.AssetRoles, assetsById, pilot, ship));
        plan.Requirements.Add(ResolvePilotBaseToken(pilot, pilotLink, knowledgeBase, assetsById));
        plan.Requirements.Add(RuntimeRequirement(ShipPackageRoles.Base, $"First Edition {Title(ship?.Size)} base generated by the runtime object builder."));
        plan.Requirements.Add(RuntimeRequirement(ShipPackageRoles.Peg, "Peg generated by the runtime object builder."));

        plan.PackageStatus = DetermineStatus(plan);
        return plan;
    }

    private static FirstEditionShipPackageRequirement ResolvePilotBaseToken(
        FirstEditionPilot pilot,
        PilotLink? pilotLink,
        UnifiedKnowledgeBase knowledgeBase,
        IReadOnlyDictionary<string, KnowledgeBaseAsset> assetsById)
    {
        var linked = ResolveLinkedRole(ShipPackageRoles.PilotBaseToken, true, pilotLink?.AssetRoles, assetsById, pilot, null);
        if (linked.ResolutionStatus is "Resolved" or "Ambiguous") return linked;

        var faction = Normalize(pilot.Faction);
        var ship = Normalize(pilot.ShipId);
        var pilotId = Normalize(pilot.Id);
        var expectedFolder = $"assets/generated/PilotBaseToken/{faction}/{ship}/";
        var generated = knowledgeBase.Domains.Assets
            .Where(x => x.Warehouse.Equals("generated", StringComparison.OrdinalIgnoreCase))
            .Where(x => IsGeneratedPilotTokenMatch(x.RepositoryPath, expectedFolder, pilotId))
            .OrderBy(x => x.RepositoryPath, StringComparer.OrdinalIgnoreCase)
            .Select(x => ToAsset(x, 1000, "high", "canonical generated First Edition pilot base token"))
            .ToList();

        if (generated.Count == 1)
        {
            linked.ResolutionStatus = "Resolved";
            linked.ResolutionSource = "UKB generated-token fallback";
            linked.ResolutionMethod = "Normalised canonical pilot identity";
            linked.SelectedAsset = generated[0];
            linked.Candidates = generated;
            linked.Note = "Resolved from the canonical generated PilotBaseToken path because pilot-links predates the generated-token import.";
        }
        else if (generated.Count > 1)
        {
            linked.ResolutionStatus = "Ambiguous";
            linked.ResolutionSource = "UKB generated-token fallback";
            linked.ResolutionMethod = "Normalised canonical pilot identity";
            linked.Candidates = generated;
            linked.Note = "Multiple canonical generated pilot base tokens matched.";
        }

        return linked;
    }

    private static bool IsGeneratedPilotTokenMatch(string repositoryPath, string expectedFolder, string normalizedPilotId)
    {
        var path = repositoryPath.Replace('\\', '/');
        if (!path.StartsWith(expectedFolder, StringComparison.OrdinalIgnoreCase)) return false;
        var fileName = Path.GetFileNameWithoutExtension(path);
        var markerIndex = fileName.IndexOf("__pilot-", StringComparison.OrdinalIgnoreCase);
        if (markerIndex <= 0) return false;
        return Normalize(fileName[..markerIndex]).Equals(normalizedPilotId, StringComparison.OrdinalIgnoreCase);
    }

    private static FirstEditionShipPackageRequirement ResolveLinkedRole(
        string role,
        bool required,
        IReadOnlyList<LinkAssetRole>? roles,
        IReadOnlyDictionary<string, KnowledgeBaseAsset> assetsById,
        FirstEditionPilot pilot,
        FirstEditionShip? ship)
    {
        var result = new FirstEditionShipPackageRequirement { Role = role, Required = required };
        var linkedRole = roles?.FirstOrDefault(x => x.Role.Equals(role, StringComparison.OrdinalIgnoreCase));
        if (linkedRole is null || linkedRole.Candidates.Count == 0)
        {
            result.Note = "No linked UKB candidate is available.";
            return result;
        }

        var candidates = linkedRole.Candidates
            .Where(x => assetsById.ContainsKey(x.AssetId))
            .GroupBy(x => x.AssetId, StringComparer.OrdinalIgnoreCase)
            .Select(group => group.OrderByDescending(x => x.Score).First())
            .Select(x => ToAsset(assetsById[x.AssetId], x.Score, x.Confidence, x.Reasons.ToArray()))
            .ToList();

        foreach (var candidate in candidates)
            candidate.ResolverScore = CalculateResolverScore(role, candidate, pilot, ship);

        result.Candidates = candidates
            .OrderByDescending(x => x.ResolverScore)
            .ThenByDescending(x => x.Score)
            .ThenBy(x => x.RepositoryPath, StringComparer.OrdinalIgnoreCase)
            .ToList();
        result.ResolutionSource = "UKB deterministic role resolver";

        if (result.Candidates.Count == 0)
        {
            result.Note = "Linked candidates were absent from the current knowledge base.";
            return result;
        }

        var eligible = ApplyAuthoritativeRoleFilter(role, result.Candidates, pilot);
        var selected = eligible
            .OrderByDescending(x => x.ResolverScore)
            .ThenByDescending(x => x.Score)
            .ThenBy(x => CanonicalPathRank(role, x.RepositoryPath))
            .ThenBy(x => x.RepositoryPath, StringComparer.OrdinalIgnoreCase)
            .First();

        result.ResolutionStatus = "Resolved";
        result.SelectedAsset = selected;
        result.AlternateAssets = result.Candidates
            .Where(x => !x.AssetId.Equals(selected.AssetId, StringComparison.OrdinalIgnoreCase))
            .ToList();
        result.ResolutionMethod = ResolutionMethod(role, selected, result.AlternateAssets.Count);
        result.Note = result.AlternateAssets.Count == 0
            ? "A single valid candidate was resolved."
            : $"Selected one canonical asset deterministically; {result.AlternateAssets.Count} valid alternate candidate(s) are retained for package variants and audit.";
        return result;
    }

    private static IReadOnlyList<FirstEditionShipPackageAsset> ApplyAuthoritativeRoleFilter(
        string role,
        IReadOnlyList<FirstEditionShipPackageAsset> candidates,
        FirstEditionPilot pilot)
    {
        if (!role.Equals(ShipPackageRoles.PilotCard, StringComparison.OrdinalIgnoreCase)) return candidates;

        var pilotId = Normalize(pilot.Id);
        var official = candidates
            .Where(x => x.Warehouse.Equals("xwing-data", StringComparison.OrdinalIgnoreCase))
            .Where(x => x.RepositoryPath.Replace('\\', '/').Contains("/images/pilots/", StringComparison.OrdinalIgnoreCase))
            .Where(x => Normalize(Path.GetFileNameWithoutExtension(x.RepositoryPath)).Equals(pilotId, StringComparison.OrdinalIgnoreCase))
            .ToList();

        return official.Count > 0 ? official : candidates;
    }

    private static int CalculateResolverScore(
        string role,
        FirstEditionShipPackageAsset candidate,
        FirstEditionPilot pilot,
        FirstEditionShip? ship)
    {
        var path = candidate.RepositoryPath.Replace('\\', '/');
        var normalizedPath = Normalize(path);
        var score = candidate.Score * 100;
        score += SourcePriority(role, candidate.Warehouse);

        var shipId = Normalize(pilot.ShipId);
        var pilotId = Normalize(pilot.Id);
        if (normalizedPath.Contains(shipId, StringComparison.OrdinalIgnoreCase)) score += 2500;
        if (normalizedPath.Contains(pilotId, StringComparison.OrdinalIgnoreCase)) score += 3500;

        if (role.Equals(ShipPackageRoles.PilotCard, StringComparison.OrdinalIgnoreCase))
        {
            if (candidate.Warehouse.Equals("xwing-data", StringComparison.OrdinalIgnoreCase) &&
                path.Contains("/images/pilots/", StringComparison.OrdinalIgnoreCase)) score += 20000;
            if (Normalize(Path.GetFileNameWithoutExtension(path)).Equals(pilotId, StringComparison.OrdinalIgnoreCase)) score += 15000;
        }
        else if (role.Equals(ShipPackageRoles.DialTexture, StringComparison.OrdinalIgnoreCase))
        {
            if (candidate.Warehouse.Equals("legacy1e-non-pilot", StringComparison.OrdinalIgnoreCase)) score += 12000;
            if (candidate.Warehouse.Equals("legacy1e", StringComparison.OrdinalIgnoreCase)) score += 10000;
        }
        else if (role.Equals(ShipPackageRoles.ShipModel, StringComparison.OrdinalIgnoreCase))
        {
            var file = Normalize(Path.GetFileNameWithoutExtension(path));
            if (file.Equals(shipId, StringComparison.OrdinalIgnoreCase)) score += 5000;
            if (file.EndsWith("v2", StringComparison.OrdinalIgnoreCase) || file.EndsWith("v1", StringComparison.OrdinalIgnoreCase)) score -= 250;
        }
        else if (role.Equals(ShipPackageRoles.ShipTexture, StringComparison.OrdinalIgnoreCase))
        {
            var file = Normalize(Path.GetFileNameWithoutExtension(path));
            if (file is "standard" or "default") score += 4000;
            if (file.Contains("grey", StringComparison.OrdinalIgnoreCase)) score += 1500;
            if (path.Contains("/textures/1/", StringComparison.OrdinalIgnoreCase)) score -= 100;
        }

        return score;
    }

    private static int SourcePriority(string role, string warehouse)
    {
        if (role.Equals(ShipPackageRoles.PilotCard, StringComparison.OrdinalIgnoreCase))
            return warehouse.ToLowerInvariant() switch
            {
                "xwing-data" => 8000,
                "generated" => 7000,
                "legacy1e" => 6000,
                "legacy1e-non-pilot" => 5500,
                "unified25" => 2000,
                _ => 1000
            };

        if (role.Equals(ShipPackageRoles.DialTexture, StringComparison.OrdinalIgnoreCase))
            return warehouse.ToLowerInvariant() switch
            {
                "generated" => 8000,
                "legacy1e-non-pilot" => 7500,
                "legacy1e" => 7000,
                "xwing-data" => 5000,
                "unified25" => 2000,
                _ => 1000
            };

        return warehouse.ToLowerInvariant() switch
        {
            "generated" => 8000,
            "generated-pilot-tokens" => 7900,
            "legacy1e" => 7000,
            "legacy1e-non-pilot" => 6900,
            "xwing-data" => 6000,
            "unified25" => 5000,
            _ => 1000
        };
    }

    private static int CanonicalPathRank(string role, string path)
    {
        path = path.Replace('\\', '/');
        var file = Normalize(Path.GetFileNameWithoutExtension(path));
        if (role.Equals(ShipPackageRoles.ShipTexture, StringComparison.OrdinalIgnoreCase))
        {
            if (file == "standard") return 0;
            if (file.Contains("grey", StringComparison.OrdinalIgnoreCase)) return 1;
            if (file.Contains("blue", StringComparison.OrdinalIgnoreCase)) return 2;
        }
        if (role.Equals(ShipPackageRoles.ShipModel, StringComparison.OrdinalIgnoreCase))
        {
            if (!file.EndsWith("v1", StringComparison.OrdinalIgnoreCase) && !file.EndsWith("v2", StringComparison.OrdinalIgnoreCase)) return 0;
        }
        return 10;
    }

    private static string ResolutionMethod(string role, FirstEditionShipPackageAsset selected, int alternateCount)
    {
        if (role.Equals(ShipPackageRoles.PilotCard, StringComparison.OrdinalIgnoreCase) && selected.Warehouse.Equals("xwing-data", StringComparison.OrdinalIgnoreCase))
            return "Authoritative xwing-data pilot-card path and exact normalised pilot identity";
        if (role.Equals(ShipPackageRoles.DialTexture, StringComparison.OrdinalIgnoreCase))
            return "First Edition dial source preference, link evidence, content deduplication and stable path ordering";
        if (role.Equals(ShipPackageRoles.ShipModel, StringComparison.OrdinalIgnoreCase))
            return alternateCount > 0 ? "Canonical model selected; alternate model variants retained" : "Canonical model selected";
        if (role.Equals(ShipPackageRoles.ShipTexture, StringComparison.OrdinalIgnoreCase))
            return alternateCount > 0 ? "Canonical texture selected; alternate colour/texture variants retained" : "Canonical texture selected";
        return "Deterministic role-aware resolver score";
    }

    private static FirstEditionShipPackageRequirement RuntimeRequirement(string role, string note) => new()
    {
        Role = role,
        Required = true,
        ResolutionStatus = "Resolved",
        ResolutionSource = "Runtime definition",
        ResolutionMethod = "First Edition runtime object definition",
        Note = note
    };

    private static string DetermineStatus(FirstEditionShipPackagePlan plan)
    {
        if (plan.ValidationErrors.Count > 0) return ShipPackageStatuses.InvalidSemanticData;
        if (plan.Requirements.Any(x => x.Required && x.ResolutionStatus == "Ambiguous")) return ShipPackageStatuses.AmbiguousRequiredAssets;
        if (plan.Requirements.Any(x => x.Required && x.ResolutionStatus != "Resolved")) return ShipPackageStatuses.UnresolvedRequiredAssets;
        if (plan.Requirements.Any(x => !x.Required && x.ResolutionStatus != "Resolved")) return ShipPackageStatuses.ReadyWithOptionalAssetsMissing;
        return ShipPackageStatuses.Ready;
    }

    private static void PopulateSummary(FirstEditionShipPackagePlanDocument document, FirstEditionRepository repository)
    {
        var required = document.Packages.SelectMany(x => x.Requirements).Where(x => x.Required).ToList();
        document.Summary = new FirstEditionShipPackagePlanSummary
        {
            ShipCount = repository.Ships.Count,
            PilotCount = repository.Pilots.Count,
            PackageCount = document.Packages.Count,
            ReadyCount = document.Packages.Count(x => x.PackageStatus == ShipPackageStatuses.Ready),
            ReadyWithOptionalAssetsMissingCount = document.Packages.Count(x => x.PackageStatus == ShipPackageStatuses.ReadyWithOptionalAssetsMissing),
            UnresolvedRequiredAssetsCount = document.Packages.Count(x => x.PackageStatus == ShipPackageStatuses.UnresolvedRequiredAssets),
            AmbiguousRequiredAssetsCount = document.Packages.Count(x => x.PackageStatus == ShipPackageStatuses.AmbiguousRequiredAssets),
            InvalidSemanticDataCount = document.Packages.Count(x => x.PackageStatus == ShipPackageStatuses.InvalidSemanticData),
            RequiredRoleCount = required.Count,
            ResolvedRequiredRoleCount = required.Count(x => x.ResolutionStatus == "Resolved"),
            AmbiguousRequiredRoleCount = required.Count(x => x.ResolutionStatus == "Ambiguous"),
            MissingRequiredRoleCount = required.Count(x => x.ResolutionStatus == "Missing"),
            RequirementsWithAlternatesCount = required.Count(x => x.AlternateAssets.Count > 0)
        };
    }

    private static ShipLink? FindShipLink(ShipLinkDocument document, string shipId) =>
        document.Ships.FirstOrDefault(x => x.TargetId.Equals(shipId, StringComparison.OrdinalIgnoreCase)
                                           || x.SourceId.Equals(shipId, StringComparison.OrdinalIgnoreCase));

    private static PilotLink? FindPilotLink(PilotLinkDocument document, FirstEditionPilot pilot) =>
        document.Pilots.FirstOrDefault(x =>
            x.TargetId.Equals(pilot.Id, StringComparison.OrdinalIgnoreCase)
            && x.ShipId.Equals(pilot.ShipId, StringComparison.OrdinalIgnoreCase)
            && x.Faction.Equals(pilot.Faction, StringComparison.OrdinalIgnoreCase));

    private static T LoadLinks<T>(string path) where T : new()
    {
        if (!File.Exists(path)) return new T();
        return JsonSerializer.Deserialize<T>(File.ReadAllText(path), JsonOptions) ?? new T();
    }

    private static FirstEditionShipPackageAsset ToAsset(KnowledgeBaseAsset asset, int score, string confidence, params string[] reasons) => new()
    {
        AssetId = asset.AssetId,
        RepositoryPath = asset.RepositoryPath,
        Warehouse = asset.Warehouse,
        AssetType = asset.AssetType,
        Score = score,
        Confidence = confidence,
        Reasons = reasons.ToList()
    };

    private static string Normalize(string value) => new(value.ToLowerInvariant().Where(char.IsLetterOrDigit).ToArray());
    private static string Title(string? value) => string.IsNullOrWhiteSpace(value) ? "unknown" : char.ToUpperInvariant(value[0]) + value[1..].ToLowerInvariant();

    private sealed class ShipLinkDocument { public List<ShipLink> Ships { get; set; } = new(); }
    private sealed class PilotLinkDocument { public List<PilotLink> Pilots { get; set; } = new(); }
    private sealed class ShipLink { public string SourceId { get; set; } = ""; public string TargetId { get; set; } = ""; public List<LinkAssetRole> AssetRoles { get; set; } = new(); }
    private sealed class PilotLink { public string TargetId { get; set; } = ""; public string ShipId { get; set; } = ""; public string Faction { get; set; } = ""; public List<LinkAssetRole> AssetRoles { get; set; } = new(); }
    private sealed class LinkAssetRole { public string Role { get; set; } = ""; public List<LinkCandidate> Candidates { get; set; } = new(); }
    private sealed class LinkCandidate { public string AssetId { get; set; } = ""; public int Score { get; set; } public string Confidence { get; set; } = ""; public List<string> Reasons { get; set; } = new(); }
}
