using UnifiedToolkit.Models;

namespace UnifiedToolkit.Reports;

public sealed class RepoStructureReport : CsvReport
{
    public override string FileName => "repo-folders.csv";

    public override void Generate(
        TtsGame game,
        IReadOnlyList<TtsObject> objects,
        string reportsFolder)
    {
        throw new NotSupportedException(
            "RepoStructureReport is generated by RepoCommand, not AnalyseCommand.");
    }

    public void Generate(
        IReadOnlyList<RepoFileEntry> files,
        string reportsFolder)
    {
        using var writer = CreateWriter(reportsFolder, FileName);

        writer.WriteLine("Folder,Total,Lua,Xml,Json,Images,Models,Text,Other,TotalSizeBytes,TotalLines");

        foreach (var group in files
                     .GroupBy(x => GetFolder(x.Path))
                     .OrderBy(x => x.Key))
        {
            writer.WriteLine(string.Join(",",
                Csv(group.Key),
                Csv(group.Count().ToString()),
                Csv(group.Count(x => x.Category == "Lua" || x.Category == "TTS Lua").ToString()),
                Csv(group.Count(x => x.Category == "XML").ToString()),
                Csv(group.Count(x => x.Category == "JSON").ToString()),
                Csv(group.Count(x => x.Category == "Image").ToString()),
                Csv(group.Count(x => x.Category == "Model").ToString()),
                Csv(group.Count(x => x.Category == "Text").ToString()),
                Csv(group.Count(x => x.Category == "Other").ToString()),
                Csv(group.Sum(x => x.SizeBytes).ToString()),
                Csv(group.Sum(x => x.LineCount).ToString())));
        }
    }

    private static string GetFolder(string path)
    {
        var folder = Path.GetDirectoryName(path);
        return string.IsNullOrWhiteSpace(folder) ? "." : folder.Replace('\\', '/');
    }
}