using UnifiedToolkit.Models;

namespace UnifiedToolkit.Reports;

public sealed class RepoLuaReport : CsvReport
{
    public override string FileName => "repo-lua.csv";

    public override void Generate(
        TtsGame game,
        IReadOnlyList<TtsObject> objects,
        string reportsFolder)
    {
        throw new NotSupportedException(
            "RepoLuaReport is generated by RepoCommand, not AnalyseCommand.");
    }

    public void Generate(
        IReadOnlyList<RepoFileEntry> files,
        string repoFolder,
        string reportsFolder)
    {
        using var writer = CreateWriter(reportsFolder, FileName);

        writer.WriteLine("Path,Lines,Folder,HasSpawnObject,HasCreateButton,HasOnLoad,HasOnSave,HasJsonDecode,HasJsonEncode,HasShip,HasPilot,HasUpgrade,HasDial");

        foreach (var file in files
                     .Where(x => x.Extension == ".lua" || x.Extension == ".ttslua")
                     .OrderByDescending(x => x.LineCount)
                     .ThenBy(x => x.Path))
        {
            var fullPath = Path.Combine(repoFolder, file.Path);

            string text;

            try
            {
                text = File.ReadAllText(fullPath);
            }
            catch
            {
                continue;
            }

            writer.WriteLine(string.Join(",",
                Csv(file.Path),
                Csv(file.LineCount.ToString()),
                Csv(GetFolder(file.Path)),
                Csv(Contains(text, "spawnObject").ToString()),
                Csv(Contains(text, "createButton").ToString()),
                Csv(Contains(text, "function onLoad").ToString()),
                Csv(Contains(text, "function onSave").ToString()),
                Csv(Contains(text, "JSON.decode").ToString()),
                Csv(Contains(text, "JSON.encode").ToString()),
                Csv(Contains(text, "ship").ToString()),
                Csv(Contains(text, "pilot").ToString()),
                Csv(Contains(text, "upgrade").ToString()),
                Csv(Contains(text, "dial").ToString())));
        }
    }

    private static bool Contains(string text, string value)
    {
        return text.Contains(value, StringComparison.OrdinalIgnoreCase);
    }

    private static string GetFolder(string path)
    {
        var folder = Path.GetDirectoryName(path);
        return string.IsNullOrWhiteSpace(folder) ? "." : folder.Replace('\\', '/');
    }
}