using UnifiedToolkit.Models;

namespace UnifiedToolkit.Reports;

public sealed class RepoSourceReport : CsvReport
{
    public override string FileName => "repo-source.csv";

    public override void Generate(
        TtsGame game,
        IReadOnlyList<TtsObject> objects,
        string reportsFolder)
    {
        throw new NotSupportedException(
            "RepoSourceReport is generated by RepoCommand, not AnalyseCommand.");
    }

    public void Generate(
        IReadOnlyList<LuaFileInfo> luaFiles,
        string reportsFolder)
    {
        using var writer = CreateWriter(reportsFolder, FileName);

        writer.WriteLine("Path,Folder,Lines,FunctionCount,RequireCount,UsesSpawnObject,UsesSpawnObjectData,UsesTakeObject,UsesCreateButton,UsesJsonDecode,UsesJsonEncode,Functions,Requires");

        foreach (var file in luaFiles.OrderByDescending(x => x.Functions.Count).ThenBy(x => x.Path))
        {
            writer.WriteLine(string.Join(",",
                Csv(file.Path),
                Csv(file.Folder),
                Csv(file.LineCount.ToString()),
                Csv(file.Functions.Count.ToString()),
                Csv(file.Requires.Count.ToString()),
                Csv(file.UsesSpawnObject.ToString()),
                Csv(file.UsesSpawnObjectData.ToString()),
                Csv(file.UsesTakeObject.ToString()),
                Csv(file.UsesCreateButton.ToString()),
                Csv(file.UsesJsonDecode.ToString()),
                Csv(file.UsesJsonEncode.ToString()),
                Csv(string.Join(" | ", file.Functions)),
                Csv(string.Join(" | ", file.Requires))));
        }
    }
}