using UnifiedToolkit.Models;

namespace UnifiedToolkit.Reports;

public sealed class ShipsReport : CsvReport
{
    public override string FileName => "ships.csv";

    public override void Generate(
        TtsGame game,
        IReadOnlyList<TtsObject> objects,
        string reportsFolder)
    {
        throw new NotSupportedException(
            "ShipsReport is generated by ShipsCommand, not AnalyseCommand.");
    }

    public void Generate(IReadOnlyList<ShipDefinition> ships, string reportsFolder)
    {
        using var writer = CreateWriter(reportsFolder, FileName);

        writer.WriteLine("Id,Name,Size,Faction,SourceFile,SourceLine");

        foreach (var ship in ships.OrderBy(x => x.Name).ThenBy(x => x.Id))
        {
            writer.WriteLine(string.Join(",",
                Csv(ship.Id),
                Csv(ship.Name),
                Csv(ship.Size),
                Csv(ship.Faction),
                Csv(ship.SourceFile),
                Csv(ship.SourceLine.ToString())));
        }
    }
}
