using UnifiedToolkit.Models;

namespace UnifiedToolkit.Reports;

public sealed class SourceModulesReport : CsvReport
{
    public override string FileName => "source-modules.csv";

    public override void Generate(
        TtsGame game,
        IReadOnlyList<TtsObject> objects,
        string reportsFolder)
    {
        throw new NotSupportedException(
            "SourceModulesReport is generated by RepoCommand, not AnalyseCommand.");
    }

    public void Generate(SourceModel source, string reportsFolder)
    {
        using var writer = CreateWriter(reportsFolder, FileName);

        writer.WriteLine("Module,Folder,Files,Lines,Functions,Requires,UsesSpawnObject,UsesSpawnObjectData,UsesTakeObject,UsesCreateButton");

        foreach (var module in source.Modules
                     .OrderByDescending(x => x.TotalLines)
                     .ThenBy(x => x.Name))
        {
            writer.WriteLine(string.Join(",",
                Csv(module.Name),
                Csv(module.Folder),
                Csv(module.FileCount.ToString()),
                Csv(module.TotalLines.ToString()),
                Csv(module.FunctionCount.ToString()),
                Csv(module.RequireCount.ToString()),
                Csv(module.UsesSpawnObject.ToString()),
                Csv(module.UsesSpawnObjectData.ToString()),
                Csv(module.UsesTakeObject.ToString()),
                Csv(module.UsesCreateButton.ToString())));
        }
    }
}